# 异常

```
class Ex extends Exception
{//自定义异常类
  String s = "Exx";
}

class B
{
  void fun(int x) throws Ex
  {//可以抛出异常的函数，不能直接被调用，需要在try、catch中调用
    if(10 == x)
    {
      throw new Ex();
    }
  }
  
  
  public void ProcessEx()
  {
    try{
      fun(10);
    }catch(Ex e)
    {
      System.out.println(e.s);
    }
  }
}
``
